[
  uuid(467946CF-A73A-4084-B226-57C0FA897CBF), 
  version(1.0), 
  helpstring("ExIRCPlugin Library")
    
]
library ExIRCPlugin
{

  importlib("Exodus.exe");
  importlib("stdole2.tlb");

  [
    uuid(5B2D612D-7F76-4496-A6C6-6E7187D1F57F), 
    version(1.0), 
    helpstring("IRCPlugin Object")
  ]
  coclass IRCPlugin
  {
    [default] interface IExodusPlugin;
  };

  [
    uuid(1D9F8982-BCDC-49FF-95C9-B87BAE450977), 
    version(1.0), 
    helpstring("IRCRoomPlugin Object")
  ]
  coclass IRCRoomPlugin
  {
    [default] interface IExodusChatPlugin;
  };

}; 