[
  uuid(4F0D5848-3AA1-4BCF-9116-870104CA12DD), 
  version(1.0), 
  helpstring("ExHTMLLogger Library"), 
  custom(DE77BA64-517C-11D1-A2DA-0000F8773CE9, 100663657), 
  custom(DE77BA63-517C-11D1-A2DA-0000F8773CE9, 1141255954), 
  custom(DE77BA65-517C-11D1-A2DA-0000F8773CE9, "Created by MIDL version 6.00.0361 at Wed Mar 01 16:32:34 2006\n")
    
]
library ExHTMLLogger
{

  importlib("stdole2.tlb");
  importlib("Exodus.exe");

  [
    uuid(BA304092-987A-42C3-A4CC-40D196BE1A4F), 
    version(1.0), 
    helpstring("HTMLLogger Object")
  ]
  coclass HTMLLogger
  {
    [default] interface IExodusPlugin;
    interface IExodusLogger;
  };

};