  !insertmacro MUI_DESCRIPTION_TEXT ${SEC_ExImportAIM} $(DESC_ExImportAIM)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC_ExAspell} $(DESC_ExAspell)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC_ExImportICQ} $(DESC_ExImportICQ)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC_ExJabberStats} $(DESC_ExJabberStats)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC_ExWordSpeller} $(DESC_ExWordSpeller)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC_ExNetMeeting} $(DESC_ExNetMeeting)
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC_ExRosterTools} $(DESC_ExRosterTools)
