[
  uuid(5EA5A7C9-CA6B-4F61-8FF1-95BFAD75397F), 
  version(1.0), 
  helpstring("RosterTools Library"), 
  custom(DE77BA64-517C-11D1-A2DA-0000F8773CE9, 100663657), 
  custom(DE77BA63-517C-11D1-A2DA-0000F8773CE9, 1055786581), 
  custom(DE77BA65-517C-11D1-A2DA-0000F8773CE9, "Created by MIDL version 6.00.0361 at Mon Jun 16 12:03:01 2003\n")
    
]
library RosterTools
{

  importlib("Exodus.exe");
  importlib("stdole2.tlb");

  [
    uuid(F4DAE94B-7B21-4576-A5D0-573A4E2CBD65), 
    version(1.0)
  ]
  coclass RosterPlugin
  {
    [default] interface IExodusPlugin;
  };

}; 