[
  uuid(78FCE930-6D97-4E80-A634-59897D6E8BB2), 
  version(1.0), 
  helpstring("TestPlugin Library")
    
]
library TestPlugin
{

  importlib("Exodus.exe");
  importlib("STDOLE2.TLB");

  [
    uuid(AE5CDE9B-CFD3-4BE9-9855-C1A1BD52A089), 
    version(1.0), 
    helpstring("Dispatch interface for TesterPlugin Object"), 
    dual, 
    oleautomation
  ]
   interface ITesterPlugin: IExodusPlugin
  {
  };

  [
    uuid(DE6D1148-AC93-412F-AF4B-F26C24136D2C), 
    version(1.0), 
    helpstring("TesterPlugin Object")
  ]
  coclass TesterPlugin
  {
    [default] interface IExodusPlugin;
  };

}; 