[
  uuid(ABFF5177-A3CD-44C7-9005-24BD069C1F5D), 
  version(1.0), 
  helpstring("ExImportICQ Library")
    
]
library ExImportICQ
{

  importlib("Exodus.exe");
  importlib("stdole2.tlb");

  [
    uuid(AF223E4A-369F-4EF3-BC15-A6A26409AA56), 
    version(1.0)
  ]
  coclass ICQImportPlugin
  {
    [default] interface IExodusPlugin;
  };

}; 